package:
  name: pydicom
  version: 1.0.0alpha

source:
    git_url: git@github.com:darcymason/pydicom.git
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - anyjson:main
    #
    # Would call anyjson.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - python-dateutil

  run:
    - python
    - python-dateutil

test:
  # Python imports
  imports:
    - pydicom

  #commands:
  #  - python setup.py --quiet test
  # setup.py not found.. tests are apparently run outside of work dir

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - unittest2  # [py26]
    - setuptools
    - six
    #- numpy
    #- gdcm

about:
  home: https://github.com/darcymason/pydicom/
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml